### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by SolitudeSF** [Nimaoth/Absytree#3]
`nimble build` results in `Error: cannot open '/home/solitude/git/app/Absytree/src/ast.nim'`

**Comment by Nimaoth** [comment]
Try `nimble buildDesktop` instead of `nimble build`

**Comment by SolitudeSF** [comment]
why not specify proper `bin` in nimble file?

**Comment by SolitudeSF** [comment]
also, the task executes nim, without nimble, bypassing any package management.

**Comment by Nimaoth** [comment]
I think the reason I went with this way was because running `nimble build` always also checked the dependencies which slowed down the build by a few seconds, but invoking `nim` directly (or through a nimble task) didn't do that and so was faster. But I'll try to make `nimble build` work as well again, no reason why it shouldn't work ^^
