### ISSUE TITLE
helix/kakoune keybindings?

### ISSUE THREAD

**Issue by SolitudeSF** [Nimaoth/Absytree#4]
Is selection first workflow supported or possible to implement with a plugin?

**Comment by Nimaoth** [comment]
The plan is that it's possible, but since I'm mainly using vim keybindings I haven't done much work on that. There is https://github.com/Nimaoth/Absytree/blob/main/config/keybindings_helix.nim where I started working on helix keybindings a bit but it's far from complete. Contributions here are welcome :)
