### ISSUE TITLE
Double click does nothing while triple click works.

### ISSUE THREAD

**Issue by treeform** [Nimaoth/Absytree#7]
I expected double click to select a word, but nothing happens.

Triple click selects a line, I would prefer it selected a paragraph, but it is acceptable.

**Comment by Nimaoth** [comment]
Fixed double click. I also added an option to run a custom command when single/double/triple clicking so you can change it to select a paragraph instead of a line (or do whatever else).
I added basic instructions [here](https://github.com/Nimaoth/Absytree/blob/main/docs/getting_started.md#mouse-settings) (and an example in [here](https://github.com/Nimaoth/Absytree/blob/2ab9bc5fcea0fd1fdaa774f73f3d59efcde98e12/config/absytree_config.nim#L85))
